### ISSUE TITLE
Add support to change version, remove or add packages ??

### ISSUE THREAD

**Issue by vinicioslc** [b-connect/vsc-pubmanager#1]
Will be nice if soon this package can do some these features...
Support to change package version/select from list
Remove package from pubspec
Add package to pubspec
what you think ? 
an what is the material/videos/documentation that i need learn to add this support to the plugin ?

**Comment by erik-seifert** [comment]
Learning to support a extension:
https://code.visualstudio.com/api/get-started/your-first-extension

**Comment by vinicioslc** [comment]
Oh great, Thanks !!
